FROM python:3.9-slim

WORKDIR /app

COPY ./URL_shortening.py /app/
COPY ./database.py /app/
COPY ./requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=URL_shortening.py

CMD ["flask", "run", "--host=0.0.0.0"]
